"""Built-in heudiconv heuristic template for ``fmriflow convert heuristics create``."""

from __future__ import annotations


def render_template(
    name: str,
    description: str | None = None,
    tasks: list[str] | None = None,
) -> str:
    """Render a skeleton heudiconv heuristic file."""
    desc_block = description or f"Heuristic for {name}."
    tasks_str = ", ".join(tasks) if tasks else "task1, task2"

    return f'''\
"""
Heuristic file for {name}.

{desc_block}

Tasks: {tasks_str}

YYYYMMDD : initial scaffold (auto-generated by fmriflow)
"""
import re
from collections import defaultdict


POPULATE_INTENDED_FOR_OPTS = {{
    'matching_parameters': ['Shims'],
    'criterion': 'Closest',
}}


# ── Classification ──────────────────────────────────────────

def _is_anat(seq) -> bool:
    """Return True if *seq* is an anatomical (e.g. T1w MPRAGE)."""
    sd = seq.series_description.lower()
    return "t1" in sd or "mprage" in sd


def _is_fmap(seq) -> bool:
    """Return True if *seq* is a fieldmap."""
    sd = seq.series_description.lower()
    return "topup" in sd or "fmap" in sd or "field_map" in sd


def _is_func(seq) -> bool:
    """Return True if *seq* is a BOLD functional run."""
    sd = seq.series_description.lower()
    if _is_fmap(seq) or _is_anat(seq):
        return False
    return "bold" in sd or "func" in sd or "task" in sd


def _is_sbref(seq) -> bool:
    """Return True if *seq* is a single-band reference."""
    return "sbref" in seq.series_description.lower()


# ── Parsing ─────────────────────────────────────────────────

def _parse_task(series_desc: str) -> str:
    """Extract the task name from a series description.

    Adjust the regex or logic to match your naming convention.
    """
    m = re.search(r'task[_-]?(\\w+)', series_desc, re.IGNORECASE)
    return m.group(1).lower() if m else "unknown"


def _parse_fmap_direction(series_desc: str) -> str | None:
    """Extract AP or PA direction from a fieldmap description."""
    sd = series_desc.lower()
    if "ap" in sd:
        return "AP"
    if "pa" in sd:
        return "PA"
    return None


# ── BIDS path builders ──────────────────────────────────────

def _create_key(template, outtype=("nii.gz",), annotation_classes=None):
    if template is None or not template:
        raise ValueError("Template must be a valid format string")
    return template, outtype, annotation_classes


def _build_base(scan_type: str) -> str:
    """sub-{{subject}}/{{session}}/<scan_type>/sub-{{subject}}_{{session}}"""
    return f"sub-{{{{subject}}}}/{{{{session}}}}/{{scan_type}}/sub-{{{{subject}}}}_{{{{session}}}}"


# ── Main heudiconv entry point ──────────────────────────────

def infotodict(seqinfo: list) -> dict:
    """Map DICOM series to BIDS file structure.

    Parameters
    ----------
    seqinfo : list
        Sequence info objects from heudiconv, each with attributes like
        ``series_id``, ``series_description``, ``image_type``, etc.

    Returns
    -------
    dict
        Mapping of (template, output_types, annotation_classes) keys
        to lists of series IDs.
    """
    info = defaultdict(list)

    anat_nr = 0
    func_nr = 0
    fmap_nr = 0

    for s in seqinfo:
        template = ""

        # ── Anatomical ──
        if _is_anat(s):
            anat_nr += 1
            template = _build_base("anat")
            if anat_nr > 1:
                template += f"_run-{{anat_nr:02d}}"
            template += "_T1w"

        # ── Fieldmap ──
        elif _is_fmap(s):
            fmap_nr += 1
            direction = _parse_fmap_direction(s.series_description)
            template = _build_base("fmap")
            if direction:
                template += f"_dir-{{direction}}"
            template += f"_run-{{fmap_nr:02d}}_epi"

        # ── SBRef — skip or handle ──
        elif _is_sbref(s):
            continue

        # ── Functional ──
        elif _is_func(s):
            func_nr += 1
            task = _parse_task(s.series_description)
            template = _build_base("func")
            template += f"_task-{{task}}_run-{{func_nr:02d}}_bold"

        if template:
            info[_create_key(template)].append(s.series_id)

    return dict(info)
'''
