"""Store scaffold — the files that make a source repo a well-formed, self-
documenting fMRIflow hub store. Written on the first publish so a fresh repo
follows (and explains) the schema without the maintainer having to know it.
"""

from __future__ import annotations

from pathlib import Path

from fmriflow.hub.manifest import KINDS, MANIFEST_NAME

# git-LFS: keep large binary feature arrays out of git object storage.
GITATTRIBUTES = "kinds/feature_array/** filter=lfs diff=lfs merge=lfs -text\n"

README = f"""# fMRIflow Artifact Hub — store

This git repository is an **fMRIflow artifact hub store**. fMRIflow reads and
writes it through a single contract:

- **`{MANIFEST_NAME}`** at the repo root is the catalog/index. fMRIflow reads it
  to know what artifacts exist and which files back them — it does **not** guess
  from the directory tree.
- Artifact files live under **`kinds/<kind>/<name>.<ext>`** (plus any sidecars).
- Large binary **`feature_array`** files are tracked with **git-LFS** (see
  `.gitattributes`).

## Artifact kinds

{chr(10).join(f"- `{k}`" for k in KINDS)}

## `{MANIFEST_NAME}` format

```json
{{
  "schema": 1,
  "artifacts": [
    {{
      "kind": "error",
      "name": "0026_fmriprep_no_t1w",
      "files": ["kinds/error/0026_fmriprep_no_t1w.yaml"],
      "sha256": "<hex>",
      "size": 1234,
      "version": "1",
      "description": "...",
      "author": "...",
      "tags": ["fmriprep"],
      "lfs": false,
      "metadata": {{}}
    }}
  ]
}}
```

`sha256` is verified on install (fail-closed). `module` entries must carry
`metadata.category`. `name` matches the identifier fMRIflow shows for that kind
(config filename, module name, error id, heuristic name, …).

## Contributing

Use **Publish** from the fMRIflow Hub UI — it stages the file under `kinds/`,
regenerates the manifest entry (hash + size), commits, and pushes a branch for
review. Or do it by hand: add the file(s), add/update the matching entry in
`{MANIFEST_NAME}`, commit, and open a PR.

_This README and `.gitattributes` were generated by fMRIflow; edit freely._
"""


def ensure_scaffold(repo_dir: Path) -> list[str]:
    """Create README.md / .gitattributes if absent. Returns files written."""
    written: list[str] = []
    ga = repo_dir / ".gitattributes"
    if not ga.exists():
        ga.write_text(GITATTRIBUTES)
        written.append(".gitattributes")
    readme = repo_dir / "README.md"
    if not readme.exists():
        readme.write_text(README)
        written.append("README.md")
    return written
